### ISSUE TITLE
Interface color

### ISSUE THREAD

**Issue by mynkow** [nickc01/Obsidian#4]
After an update of vs2022 the interface color changed for me. I have tried to reset all my settings but it remained the same. Is it an issue on my end?

![image](https://github.com/nickc01/Obsidian/assets/183151/0af2dac4-ed9c-4749-a6b8-c65c56ff8958)

**Comment by nickc01** [comment]
Hmm. It looks like with the new visual studio update, the color for those properties are controlled by the "Text Editor Language Service Items" -> "Identifier" property. You can see it affecting the color of those properties shown in pink below:

![Color Property](https://github.com/nickc01/Obsidian/assets/12601671/c4d3fed5-d1f7-42b6-b82e-a533688fd1a0)

The problem is that changing the color of "Identifier" seems to change way more than just the interfaces. It also changes the namespace labels, Type labels, enum labels, etc. So I'm not quite sure yet on how to modify the interface labels specifically. I'll see if I can do some more digging.

**Comment by nickc01** [comment]
Apparently, setting the "Identifier" value to "Default" allowed me to fix the issue. I just published a new build, and should be available to download from the Visual Studio Marketplace soon.

**Comment by mynkow** [comment]
thank you

**Comment by razor101** [comment]
Thanks for maintaining this theme! Keep up the good work

**Comment by mynkow** [comment]
hmm, I think this actually messed up with the class name color:
![image](https://github.com/nickc01/Obsidian/assets/183151/6a47cdb3-4cd3-48d6-a030-35ce381a543e)

**Comment by nickc01** [comment]
> hmm, I think this actually messed up with the class name color: ![image](https://private-user-images.githubusercontent.com/183151/332673594-6a47cdb3-4cd3-48d6-a030-35ce381a543e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NTY3NzAsIm5iZiI6MTcxNjY1NjQ3MCwicGF0aCI6Ii8xODMxNTEvMzMyNjczNTk0LTZhNDdjZGIzLTRjZDMtNDhkNi1hMDMwLTM1Y2UzODFhNTQzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxNzAxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTUyMTE2ZTE3NmNkZjgwN2JjOGZmY2Q4M2I0N2FlNjQ1NjkyNDg0M2NjZDI1ODBkOWQxMTc3ZjdjNjlmMzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mkFzRcDqZOi6BDv6GuEcb9ZHMZckl42fgedGSZIh8Ao)

This should now be fixed in the latest 2.3 release
